CREATE TABLE hackathons (
    id           UUID PRIMARY KEY,
    organizer_id UUID         NOT NULL REFERENCES students (id) ON DELETE CASCADE,
    name         VARCHAR(120) NOT NULL,
    description  VARCHAR(1000),
    status       VARCHAR(20)  NOT NULL CHECK (status IN ('OPEN', 'CLOSED', 'PUBLISHED')),
    created_at   TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_hackathons_created ON hackathons (created_at DESC);

-- Roles every team should cover, in priority order (smaller teams drop the last roles first).
CREATE TABLE hackathon_roles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hackathon_id UUID        NOT NULL REFERENCES hackathons (id) ON DELETE CASCADE,
    name         VARCHAR(60) NOT NULL,
    keywords     VARCHAR(300) NOT NULL DEFAULT '',
    position     INTEGER     NOT NULL,
    UNIQUE (hackathon_id, name),
    UNIQUE (hackathon_id, position)
);

CREATE TABLE hackathon_participants (
    hackathon_id  UUID        NOT NULL REFERENCES hackathons (id) ON DELETE CASCADE,
    student_id    UUID        NOT NULL REFERENCES students (id) ON DELETE CASCADE,
    registered_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (hackathon_id, student_id)
);

-- Ordered role preferences (rank 0 = first choice).
CREATE TABLE hackathon_role_prefs (
    hackathon_id UUID    NOT NULL,
    student_id   UUID    NOT NULL,
    rank         INTEGER NOT NULL,
    role_id      BIGINT  NOT NULL REFERENCES hackathon_roles (id) ON DELETE CASCADE,
    PRIMARY KEY (hackathon_id, student_id, rank),
    FOREIGN KEY (hackathon_id, student_id) REFERENCES hackathon_participants (hackathon_id, student_id) ON DELETE CASCADE
);

CREATE TABLE hackathon_teams (
    id           UUID PRIMARY KEY,
    hackathon_id UUID    NOT NULL REFERENCES hackathons (id) ON DELETE CASCADE,
    number       INTEGER NOT NULL,
    UNIQUE (hackathon_id, number)
);

CREATE TABLE hackathon_team_members (
    team_id    UUID             NOT NULL REFERENCES hackathon_teams (id) ON DELETE CASCADE,
    student_id UUID             NOT NULL REFERENCES students (id) ON DELETE CASCADE,
    role_id    BIGINT           NOT NULL REFERENCES hackathon_roles (id) ON DELETE CASCADE,
    fit        DOUBLE PRECISION NOT NULL,
    strength   DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (team_id, student_id)
);
