package edu.campusconnect.api;
import edu.campusconnect.model.*;import edu.campusconnect.repo.*;import edu.campusconnect.security.*;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import jakarta.servlet.http.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.http.*;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.mail.SimpleMailMessage;import org.springframework.mail.javamail.JavaMailSender;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;import org.springframework.web.server.ResponseStatusException;import java.security.*;import java.time.*;import java.util.*;import java.nio.charset.StandardCharsets;
@RestController @RequestMapping("/api/v1/auth") public class AuthController {
 private final StudentRepository students;private final EmailTokenRepository emails;private final RefreshTokenRepository refresh;private final PasswordEncoder passwords;private final JwtService jwt;private final JavaMailSender mail;private final Set<String> domains;private final String frontend;private final boolean secure;
 public AuthController(StudentRepository s,EmailTokenRepository e,RefreshTokenRepository r,PasswordEncoder p,JwtService j,JavaMailSender m,@Value("${app.approved-domains}") String domains,@Value("${app.frontend-url}") String frontend,@Value("${app.secure-cookies}") boolean secure){students=s;emails=e;refresh=r;passwords=p;jwt=j;mail=m;this.domains=new HashSet<>(Arrays.asList(domains.toLowerCase(Locale.ROOT).split(",")));this.frontend=frontend;this.secure=secure;}
 public record Register(@NotBlank @Size(max=120) String fullName,@Email @NotBlank String email,@Size(min=10,max=128) String password){}public record Login(@Email String email,String password){}public record Verify(@NotBlank String token){}public record Access(String accessToken){}public record Message(String message){}
 static String random(){byte[] b=new byte[32];new SecureRandom().nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);}static String hash(String v){try{byte[] b=MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8));return HexFormat.of().formatHex(b);}catch(Exception ex){throw new IllegalStateException(ex);}}
 @PostMapping("/register") @Transactional public ResponseEntity<Message> register(@Valid @RequestBody Register req){String email=req.email().trim().toLowerCase(Locale.ROOT);String domain=email.substring(email.lastIndexOf('@')+1);if(!domains.contains(domain))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"College email domain not approved");if(students.findByEmail(email).isPresent())throw new ResponseStatusException(HttpStatus.CONFLICT,"Email already registered");Student s=students.save(new Student(req.fullName().trim(),email,passwords.encode(req.password())));String raw=random();emails.save(new EmailToken(s,hash(raw),Instant.now().plusSeconds(1800)));SimpleMailMessage msg=new SimpleMailMessage();msg.setTo(email);msg.setFrom("noreply@campusconnect.local");msg.setSubject("Verify CampusConnect account");msg.setText("Verify your account: "+frontend+"/verify?token="+raw);mail.send(msg);return ResponseEntity.status(201).body(new Message("Check your college email for a verification link"));}
 @PostMapping("/verify") @Transactional public Message verify(@Valid @RequestBody Verify req){EmailToken t=emails.findByTokenHash(hash(req.token())).orElseThrow(()->new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid verification token"));if(t.usedAt!=null||!t.expiresAt.isAfter(Instant.now()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Expired or used verification token");t.usedAt=Instant.now();t.student.verified=true;return new Message("Email verified. You can log in.");}
 @PostMapping("/login") @Transactional public ResponseEntity<Access> login(@RequestBody Login req,HttpServletResponse res){Student s=students.findByEmail(req.email()==null?"":req.email().trim().toLowerCase(Locale.ROOT)).orElse(null);if(s==null||!passwords.matches(req.password()==null?"":req.password(),s.passwordHash)||!s.verified)throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Invalid credentials or unverified account");return session(s,res);}
 private ResponseEntity<Access> session(Student s,HttpServletResponse res){String raw=random();refresh.save(new RefreshToken(s,hash(raw),Instant.now().plus(Duration.ofDays(7))));cookie(res,raw,7*24*3600);return ResponseEntity.ok(new Access(jwt.issue(s.id)));}
 private void cookie(HttpServletResponse res,String value,int maxAge){ResponseCookie c=ResponseCookie.from("cc_refresh",value).httpOnly(true).secure(secure).sameSite("Strict").path("/api/v1/auth").maxAge(maxAge).build();res.addHeader(HttpHeaders.SET_COOKIE,c.toString());}
 @PostMapping("/refresh") @Transactional public ResponseEntity<Access> refresh(@CookieValue(name="cc_refresh",required=false) String raw,HttpServletResponse res){if(raw==null)throw new ResponseStatusException(HttpStatus.UNAUTHORIZED);RefreshToken t=refresh.findByTokenHash(hash(raw)).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED));if(t.revokedAt!=null||!t.expiresAt.isAfter(Instant.now()))throw new ResponseStatusException(HttpStatus.UNAUTHORIZED);t.revokedAt=Instant.now();return session(t.student,res);}
 @PostMapping("/logout") @Transactional public Message logout(@CookieValue(name="cc_refresh",required=false) String raw,HttpServletResponse res){if(raw!=null)refresh.findByTokenHash(hash(raw)).ifPresent(t->t.revokedAt=Instant.now());cookie(res,"",0);return new Message("Logged out");}
}
