package edu.campusconnect.api;
import edu.campusconnect.model.*;import edu.campusconnect.repo.*;import edu.campusconnect.security.CurrentStudent;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.data.redis.core.StringRedisTemplate;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;import org.springframework.web.server.ResponseStatusException;import org.springframework.http.HttpStatus;import java.time.*;import java.util.*;
@RestController @RequestMapping("/api/v1/presence") public class PresenceController {private final CurrentStudent current;private final PresenceRepository presence;private final ZoneRepository zones;private final StringRedisTemplate redis;public PresenceController(CurrentStudent c,PresenceRepository p,ZoneRepository z,StringRedisTemplate r){current=c;presence=p;zones=z;redis=r;}
 public record Checkin(@NotNull Long zoneId,@NotNull Presence.Status status){}public record PresenceView(UUID studentId,String name,String zone,String status,Instant expiresAt){}
 @GetMapping("/zones") public List<ZoneView> zones(){current.get();return zones.findByEnabledTrue().stream().map(z->new ZoneView(z.id,z.name)).toList();} public record ZoneView(Long id,String name){}
 @PostMapping("/check-in") @Transactional public PresenceView checkin(@Valid @RequestBody Checkin req){Student s=current.get();CampusZone z=zones.findById(req.zoneId()).filter(x->x.enabled).orElseThrow(()->new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid zone"));Instant expiry=Instant.now().plus(Duration.ofMinutes(15));Presence p=presence.findById(s.id).orElseGet(()->new Presence(s,z,req.status(),expiry));p.zone=z;p.status=req.status();p.expiresAt=expiry;p.updatedAt=Instant.now();presence.save(p);redis.opsForValue().set("presence:"+s.id,req.status().name()+":"+z.id,Duration.ofMinutes(15));return view(p);}
 @PostMapping("/check-out") @Transactional public Map<String,String> checkout(){Student s=current.get();presence.deleteById(s.id);redis.delete("presence:"+s.id);return Map.of("message","Checked out");}
 @GetMapping("/me") public Optional<PresenceView> mine(){Student s=current.get();return presence.findById(s.id).filter(p->p.expiresAt.isAfter(Instant.now())).map(this::view);}
 @GetMapping("/available") public List<PresenceView> available(@RequestParam(required=false) Long zoneId){current.get();return presence.findByExpiresAtAfterAndStatus(Instant.now(),Presence.Status.AVAILABLE).stream().filter(p->zoneId==null||p.zone.id.equals(zoneId)).filter(p->Boolean.TRUE.equals(redis.hasKey("presence:"+p.student.id))).map(this::view).toList();}
 private PresenceView view(Presence p){return new PresenceView(p.student.id,p.student.fullName,p.zone.name,p.status.name(),p.expiresAt);}
}
