package edu.campusconnect.api;
import edu.campusconnect.model.*;import edu.campusconnect.repo.*;import edu.campusconnect.security.CurrentStudent;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;import org.springframework.web.server.ResponseStatusException;import org.springframework.http.HttpStatus;import java.util.*;
@RestController @RequestMapping("/api/v1") public class ProfileController {private final CurrentStudent current;private final StudentSkillRepository studentSkills;private final SkillRepository skills;private final StudentSubjectRepository studentSubjects;private final SubjectRepository subjects;public ProfileController(CurrentStudent c,StudentSkillRepository ss,SkillRepository s,StudentSubjectRepository st,SubjectRepository sub){current=c;studentSkills=ss;skills=s;studentSubjects=st;subjects=sub;}
 public record Item(String name,StudentSkill.Level proficiency){}public record Profile(UUID id,String fullName,String email,String bio,List<Item> skills,List<Item> subjects){}public record Update(@NotBlank @Size(max=120) String fullName,@Size(max=500) String bio){}public record NewItem(@NotBlank @Size(max=80) String name,@NotNull StudentSkill.Level proficiency){}
 @GetMapping("/students/me") public Profile me(){Student s=current.get();return new Profile(s.id,s.fullName,s.email,s.bio,studentSkills.findByStudentId(s.id).stream().map(x->new Item(x.skill.name,x.proficiency)).toList(),studentSubjects.findByStudentId(s.id).stream().map(x->new Item(x.subject.name,x.proficiency)).toList());}
 @PutMapping("/students/me") @Transactional public Profile update(@Valid @RequestBody Update req){Student s=current.get();s.fullName=req.fullName().trim();s.bio=req.bio();return me();}
 @PostMapping("/students/me/skills") @Transactional public Profile skill(@Valid @RequestBody NewItem req){Student s=current.get();String name=req.name().trim();Skill skill=skills.findByNameIgnoreCase(name).orElseGet(()->skills.save(new Skill(name)));studentSkills.save(new StudentSkill(s,skill,req.proficiency()));return me();}
 @DeleteMapping("/students/me/skills/{id}") @Transactional public Profile deleteSkill(@PathVariable Long id){Student s=current.get();studentSkills.findByStudentId(s.id).stream().filter(x->x.skill.id.equals(id)).findFirst().ifPresent(studentSkills::delete);return me();}
 @PostMapping("/students/me/subjects") @Transactional public Profile subject(@Valid @RequestBody NewItem req){Student s=current.get();String name=req.name().trim();Subject subject=subjects.findByNameIgnoreCase(name).orElseGet(()->subjects.save(new Subject(name)));studentSubjects.save(new StudentSubject(s,subject,req.proficiency()));return me();}
 @GetMapping("/skills") public List<Skill> skills(){current.get();return skills.findAll();}
 @GetMapping("/subjects") public List<Subject> subjects(){current.get();return subjects.findAll();}
}
